#!/usr/bin/env python3
"""
Lunar Studio — release-dataset standardiser (in-place).

Walks each entry in the release config and produces the final, minimal
release layout:

    release_data/<mission>/<dem>/<region>/
        <cube_id>.cub                          # 1 full cube per orbit (LRO NAC only;
                                                # LUTI full cubes stay at source)
        jigsawErr_bundleout_points.csv          # bundle adjustment output
        site<N>/
            <cube_id>.site<N>.png               # 1 per orbit (pulled from .pixelvalue
                                                #  / .pho.campt / .campt / .<dem>.campt
                                                #  / bare .png)
            <cube_id>.site<N>.csv               # campt CSV (human-readable twin of parquet)
            <cube_id>.site<N>_zdepth.parquet    # 1 per orbit
            <cube_id>.site<N>_lola_cub_3d_comparison_{lola_3d,cub_3d,pixel_coords}.npy
            <region>_site<N>_<cube_id>.<orig_lola>.csv  (generated by lola_to_npy.py)

The standardiser:

  * Pulls PNG / parquet / campt CSV out of any ``3_view/`` subfolder found
    at site-level or at region-level (single-site Pit regions),
  * Strips the ``.echo.`` / ``.pho`` / ``.pixelvalue`` / ``.campt`` /
    ``.<dem>.campt`` infixes so only ``{cube}.site{N}.{png|csv|_zdepth.parquet}``
    remains,
  * Promotes the per-orbit full (uncropped) ``<cube_id>.echo.cub`` from the
    source tree into the region folder as ``<cube_id>.cub`` (LRO NAC only —
    LUTI entries keep their full cubes at the source tree per release plan),
  * Promotes ``jigsawErr_bundleout_points.csv`` from the source tree to the
    region folder,
  * Renames pre-existing ``.echo.site<N>_lola_cub_3d_comparison_*.npy``
    files in place to drop the ``.echo.`` infix.

With ``--clean`` the script then deletes every file under each site folder
and each region folder that is NOT on the allowlist. Defaults to
non-destructive copy+rename; pass ``--clean`` only once you have verified
the target state. Use ``--dry-run`` first to preview every action.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Sequence

try:
    import yaml
except ImportError:
    yaml = None


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(path: Path) -> dict:
    text = path.read_text()
    if path.suffix.lower() in (".yaml", ".yml"):
        if yaml is None:
            raise RuntimeError("PyYAML not installed; run `pip install pyyaml`")
        return yaml.safe_load(text)
    return json.loads(text)


@dataclass(frozen=True)
class Action:
    kind: str          # "copy" | "rename" | "delete" | "mkdir"
    src: Optional[Path]
    dst: Path

    def describe(self) -> str:
        if self.kind == "delete":
            return f"DELETE {self.dst}"
        if self.kind == "mkdir":
            return f"MKDIR  {self.dst}"
        return f"{self.kind.upper():6} {self.src} -> {self.dst}"


class Runner:
    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.counter: dict[str, int] = {"copy": 0, "rename": 0, "delete": 0,
                                        "mkdir": 0, "skip": 0}

    def do(self, action: Action) -> None:
        print("  " + ("[dry] " if self.dry_run else "") + action.describe())
        if self.dry_run:
            self.counter[action.kind] += 1
            return
        if action.kind == "mkdir":
            action.dst.mkdir(parents=True, exist_ok=True)
        elif action.kind == "copy":
            action.dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(action.src, action.dst)   # type: ignore[arg-type]
        elif action.kind == "rename":
            action.dst.parent.mkdir(parents=True, exist_ok=True)
            action.src.rename(action.dst)           # type: ignore[union-attr]
        elif action.kind == "delete":
            if action.dst.is_dir():
                shutil.rmtree(action.dst)
            elif action.dst.exists():
                action.dst.unlink()
        self.counter[action.kind] += 1

    def skip(self, msg: str) -> None:
        print(f"  skip   {msg}")
        self.counter["skip"] += 1


# ---------------------------------------------------------------------------
# File-discovery helpers
# ---------------------------------------------------------------------------

def site_png_patterns(cube_id: str, site: int) -> List[str]:
    # Preference: the photometrically-normalised raw-pixel view first
    # (.pho.pixelvalue), then plain pixelvalue, then .pho.campt, then
    # .campt / .<dem>.campt, finally bare .png. Any of these sources get
    # copied to {cube}.site{N}.png (echo / pho / pixelvalue all dropped).
    return [
        f"{cube_id}.echo.site{site}.pho.pixelvalue.png",
        f"{cube_id}.echo.site{site}.pixelvalue.png",
        f"{cube_id}.site{site}.pixelvalue.png",
        f"{cube_id}.echo.site{site}.pho.campt.png",
        f"{cube_id}.echo.site{site}.campt.png",
        f"{cube_id}.echo.site{site}.nacdtm.campt.png",
        f"{cube_id}.echo.site{site}.sldem.campt.png",
        f"{cube_id}.echo.site{site}.pho.png",
        f"{cube_id}.echo.site{site}.png",
        f"{cube_id}.site{site}.png",   # already standardised — no-op path
    ]


def site_parquet_patterns(cube_id: str, site: int) -> List[str]:
    return [
        f"{cube_id}.echo.site{site}_zdepth.parquet",
        f"{cube_id}.echo.site{site}.zdepth.parquet",
        f"{cube_id}.echo.site{site}.pho_zdepth.parquet",
        f"{cube_id}.echo.site{site}.pho.zdepth.parquet",
        f"{cube_id}.site{site}_zdepth.parquet",
    ]


def site_csv_patterns(cube_id: str, site: int) -> List[str]:
    """The campt CSV twin of the parquet — kept because parquet is binary."""
    return [
        f"{cube_id}.echo.site{site}.csv",
        f"{cube_id}.echo.site{site}.pho.csv",
        f"{cube_id}.site{site}.csv",
    ]


def first_existing(dirs: Sequence[Path], names: Sequence[str]) -> Optional[Path]:
    # Outer loop on patterns, inner on dirs: prefer the highest-priority
    # filename variant regardless of which sub-directory it sits in.
    # (A .pho.pixelvalue.png buried under site/output/ still beats a plain
    # .pho.png sitting directly in site/.)
    for n in names:
        for d in dirs:
            if not d.is_dir():
                continue
            p = d / n
            if p.exists():
                return p
    return None


# ---------------------------------------------------------------------------
# Per-site / per-region work units
# ---------------------------------------------------------------------------

def standardise_site(release_site_dir: Path, cube_ids: Iterable[str],
                     site: int, source_3view_dir: Optional[Path],
                     runner: Runner) -> None:
    """Pull png / parquet / campt csv into canonical filenames in-place."""
    search_dirs: List[Path] = []
    if release_site_dir.is_dir():
        search_dirs.append(release_site_dir)
        # Common csv2parquet / curated-view subfolders. `output/` is where
        # the csv2parquet pipeline dumps its PNG+parquet; `3_view/` (and
        # friends) hold the hand-curated 3-orbit view.
        for sub in ("output", "3_view", "2_view", "1_view"):
            p = release_site_dir / sub
            if p.is_dir():
                search_dirs.append(p)
    if source_3view_dir is not None and source_3view_dir.is_dir():
        search_dirs.append(source_3view_dir)
    if not search_dirs:
        runner.skip(f"site{site}: no directory to scan")
        return
    if not release_site_dir.exists():
        runner.do(Action("mkdir", None, release_site_dir))

    for cube_id in cube_ids:
        # PNG
        png_src = first_existing(search_dirs, site_png_patterns(cube_id, site))
        png_dst = release_site_dir / f"{cube_id}.site{site}.png"
        if png_src is None:
            runner.skip(f"site{site}: {cube_id} png not found")
        elif png_src == png_dst:
            runner.skip(f"site{site}: {cube_id} png already canonical")
        else:
            runner.do(Action("copy", png_src, png_dst))

        # Parquet
        pq_src = first_existing(search_dirs, site_parquet_patterns(cube_id, site))
        pq_dst = release_site_dir / f"{cube_id}.site{site}_zdepth.parquet"
        if pq_src is None:
            runner.skip(f"site{site}: {cube_id} parquet not found")
        elif pq_src == pq_dst:
            runner.skip(f"site{site}: {cube_id} parquet already canonical")
        else:
            runner.do(Action("copy", pq_src, pq_dst))

        # Campt CSV (the human-readable twin of the parquet)
        csv_src = first_existing(search_dirs, site_csv_patterns(cube_id, site))
        csv_dst = release_site_dir / f"{cube_id}.site{site}.csv"
        if csv_src is None:
            runner.skip(f"site{site}: {cube_id} campt csv not found")
        elif csv_src == csv_dst:
            runner.skip(f"site{site}: {cube_id} campt csv already canonical")
        else:
            runner.do(Action("copy", csv_src, csv_dst))

        # LOLA npy (.echo. → .) rename if present
        for old in release_site_dir.glob(
            f"{cube_id}.echo.site{site}_lola_cub_3d_comparison_*.npy"
        ):
            new = release_site_dir / old.name.replace(".echo.", ".")
            if new != old and not new.exists():
                runner.do(Action("rename", old, new))


def standardise_region_level(mission: str, cube_ids: Iterable[str],
                             source_dir: Optional[Path],
                             release_region_dir: Path,
                             runner: Runner) -> None:
    """Promote uncropped cubes + jigsaw CSV from source tree. LUTI entries
    are skipped (their full cubes stay at the source tree per release plan)."""
    if mission == "kplo_luti":
        runner.skip(f"region-level promote skipped for {mission}")
        return
    if source_dir is None or not source_dir.is_dir():
        runner.skip(f"region-level promote: source dir missing ({source_dir})")
        return

    release_region_dir.mkdir(parents=True, exist_ok=True)

    for cube_id in cube_ids:
        src = source_dir / f"{cube_id}.echo.cub"
        dst = release_region_dir / f"{cube_id}.cub"
        if not src.exists():
            runner.skip(f"full cube: {src.name} missing in source")
            continue
        if dst.exists() and dst.stat().st_size == src.stat().st_size:
            runner.skip(f"full cube already promoted: {dst.name}")
            continue
        runner.do(Action("copy", src, dst))

    jsrc = source_dir / "jigsawErr_bundleout_points.csv"
    jdst = release_region_dir / "jigsawErr_bundleout_points.csv"
    if jsrc.exists():
        if jdst.exists() and jdst.stat().st_size == jsrc.stat().st_size:
            runner.skip("jigsaw csv already promoted")
        else:
            runner.do(Action("copy", jsrc, jdst))
    else:
        runner.skip(f"jigsaw csv missing in source: {jsrc}")


# ---------------------------------------------------------------------------
# Cleanup (post-standardise)
# ---------------------------------------------------------------------------

REGION_KEEP_GLOBS_FILES = [
    "*.cub",
    "jigsawErr_bundleout_points.csv",
]

REGION_KEEP_GLOBS_DIRS = [
    "site[0-9]",
    "site[0-9][0-9]",
]


# Glob patterns that additionally keep the hand-placed LOLA CSVs regardless
# of their exact filename form. Everything else in a site folder that isn't
# in the per-orbit explicit keep-set is deleted.
LOLA_CSV_PATTERNS = [
    "*_PointPerRow*.csv",                  # raw LOLA PDS download
    "*_site[0-9]_*_RDR_*PointPerRow*.csv", # renamed LOLA CSV (lola_to_npy.py)
]


def matches_any(name: str, patterns: Iterable[str]) -> bool:
    return any(fnmatch.fnmatchcase(name, p) for p in patterns)


def canonical_site_names(cube_ids: Iterable[str], site: int) -> set[str]:
    """Exact filenames that are allowed to survive in a cleaned site dir."""
    keep: set[str] = set()
    for cid in cube_ids:
        keep.add(f"{cid}.site{site}.png")
        keep.add(f"{cid}.site{site}.csv")
        keep.add(f"{cid}.site{site}_zdepth.parquet")
        keep.add(f"{cid}.site{site}_lola_cub_3d_comparison_lola_3d.npy")
        keep.add(f"{cid}.site{site}_lola_cub_3d_comparison_cub_3d.npy")
        keep.add(f"{cid}.site{site}_lola_cub_3d_comparison_pixel_coords.npy")
    return keep


def cleanup_site(release_site_dir: Path, cube_ids: Iterable[str],
                 site: int, runner: Runner) -> None:
    """Keep only canonical (exact-match) per-orbit files + LOLA CSVs;
    delete everything else in the site directory recursively."""
    if not release_site_dir.is_dir():
        return
    keep = canonical_site_names(cube_ids, site)
    # Delete files in subdirs (3_view/, output/, cache/, …) recursively,
    # then drop empty subdirs, then unmatched top-level files.
    for entry in sorted(release_site_dir.rglob("*"),
                        key=lambda p: -len(p.parts)):
        if entry == release_site_dir:
            continue
        if entry.is_dir():
            try:
                next(entry.iterdir())
            except StopIteration:
                runner.do(Action("delete", None, entry))
            continue
        if entry.parent != release_site_dir:
            runner.do(Action("delete", None, entry))
            continue
        if entry.name in keep:
            continue
        if matches_any(entry.name, LOLA_CSV_PATTERNS):
            continue
        runner.do(Action("delete", None, entry))


def cleanup_region(release_region_dir: Path, cube_ids: Iterable[str],
                   runner: Runner) -> None:
    """Keep only the per-shipping-orbit full cubes + the jigsaw CSV,
    plus the site<N>/ sub-dirs. Everything else (older cubes for orbits
    not in the shipping set, stray files, intermediate dirs) is removed."""
    if not release_region_dir.is_dir():
        return
    keep_files = {f"{cid}.cub" for cid in cube_ids}
    keep_files.add("jigsawErr_bundleout_points.csv")
    for entry in release_region_dir.iterdir():
        if entry.is_dir():
            if matches_any(entry.name, REGION_KEEP_GLOBS_DIRS):
                continue
            runner.do(Action("delete", None, entry))
            continue
        if entry.name in keep_files:
            continue
        runner.do(Action("delete", None, entry))


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def orbit_has_parquet(release_region_dir: Path, cube_id: str,
                      num_sites: int) -> bool:
    """An orbit is considered shippable only if at least one of its sites
    carries a parquet. Checks every known variant and every subfolder we
    later standardise from."""
    candidates = []
    for n in range(1, num_sites + 1):
        site_dir = release_region_dir / f"site{n}"
        for sub in (site_dir, site_dir / "output", site_dir / "3_view",
                    site_dir / "2_view", site_dir / "1_view"):
            for name in site_parquet_patterns(cube_id, n):
                candidates.append(sub / name)
    return any(p.exists() for p in candidates)


def process_region(region: dict, release_root: Path, runner: Runner,
                   clean: bool) -> None:
    mission = region["mission"]
    dem = region["dem"]
    region_name = region["region"]
    reference_id = region["reference_id"]
    num_sites = int(region["num_sites"])
    configured_cube_ids: List[str] = region.get("cube_ids") or [reference_id]
    source_dir = Path(region["site_cubes_dir"])

    release_region_dir = release_root / mission / dem / region_name

    # Auto-filter: only keep orbits whose site folders actually carry a
    # parquet output. Orbits that only have a png (e.g. non-.pho. variants)
    # are not part of the shipping set — the LNEM-ready parquet is the
    # primary deliverable.
    cube_ids = [c for c in configured_cube_ids
                if orbit_has_parquet(release_region_dir, c, num_sites)]
    dropped = [c for c in configured_cube_ids if c not in cube_ids]

    print(f"\n=== {mission}/{dem}/{region_name} "
          f"(reference={reference_id}, sites={num_sites}, "
          f"orbits={len(cube_ids)}/{len(configured_cube_ids)}) ===")
    if dropped:
        print(f"  dropped orbits (no parquet): {', '.join(dropped)}")

    standardise_region_level(
        mission=mission, cube_ids=cube_ids,
        source_dir=source_dir,
        release_region_dir=release_region_dir,
        runner=runner,
    )

    for n in range(1, num_sites + 1):
        release_site = release_region_dir / f"site{n}"
        ext_3view = source_dir / "3_view" if num_sites == 1 else None
        standardise_site(
            release_site_dir=release_site,
            cube_ids=cube_ids, site=n,
            source_3view_dir=ext_3view,
            runner=runner,
        )

    if clean:
        print(f"  --- cleanup ---")
        for n in range(1, num_sites + 1):
            cleanup_site(release_region_dir / f"site{n}", cube_ids, n, runner)
        cleanup_region(release_region_dir, cube_ids, runner)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--config", type=Path, required=True,
                        help="Release config (YAML or JSON).")
    parser.add_argument("--release-root", type=Path, required=True,
                        help="Root of the release_data tree.")
    parser.add_argument("--only", nargs="+", default=None,
                        help="Limit to regions whose `region` field matches "
                             "one of these names (e.g. apollo15 vallis).")
    parser.add_argument("--clean", action="store_true",
                        help="Delete non-allowlisted files after rename/copy.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print actions but do not touch the filesystem.")
    args = parser.parse_args()

    cfg = load_config(args.config)
    if "regions" not in cfg:
        print("ERROR: config must have top-level 'regions'", file=sys.stderr)
        return 1

    regions = cfg["regions"]
    if args.only:
        wanted = set(args.only)
        regions = [r for r in regions if r["region"] in wanted]

    runner = Runner(dry_run=args.dry_run)
    for region in regions:
        process_region(region, args.release_root, runner, clean=args.clean)

    print("\n" + "=" * 60)
    print(f"Actions: copy={runner.counter['copy']}  "
          f"rename={runner.counter['rename']}  "
          f"delete={runner.counter['delete']}  "
          f"mkdir={runner.counter['mkdir']}  "
          f"skip={runner.counter['skip']}"
          + ("   [DRY-RUN]" if args.dry_run else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
